# Generated by Django 5.2.3 on 2025-06-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productrating_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Featured Product',
                'verbose_name_plural': 'Featured Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
